### ISSUE TITLE
Activate “Apply” button with Return key

### ISSUE THREAD

**Issue by florianpircher** [sindpfla98/ChangeSentenceToMieum#1]
If you want the _Apply_ key to be activated by pressing the Return key, use the `setDefaultButton` method (assuming you are using Vanilla).

Here is an example:

https://github.com/bBoxType/Kernkraft/blob/08e668ae0894280219cf47f2472ed3bd668e83dd/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py#L1070

If not, feel free to close this issue.

**Comment by sindpfla98** [comment]
I didn't use Vanilla.
