### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by schriftgestalt** [sindpfla98/ChangeSentenceToMieum#4]
I just tried the plugin and I get:
```
Details:
Traceback (most recent call last):

  File "plugin.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__

  File "__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__

ImportError: dlopen(~/Library/Application Support/Glyphs 3/Repositories/ChangeSentenceToMieum/ChangeSentenceToMieum.glyphsPlugin/Contents/Resources/pyarmor_runtime_000000/pyarmor_runtime.so, 0x0002): symbol not found in flat namespace '_PyCode_GetCode'

App:3.3-3316 Plugin:1.1.0-1 System:13.6.9
```
I’m using python 3.10.11 from python.org. When using the python from Glyphs, it works.

**Comment by sindpfla98** [comment]
I have written down the available minimum glyphs version and python version in the readme.
Minimum Glyphs version: build 3161.
Python version: 3.11.6.

**Comment by schriftgestalt** [comment]
are you sure you need python 3.11? Glyphs 3.2 only works with 3.10.

**Comment by sindpfla98** [comment]
Yes. I'm using python module 3.11.9 in version Glyphs3.2.3. If the Glyphs version is wrong, please let me know the minimum version that supports python 3.11. I'll fix it.

**Comment by schriftgestalt** [comment]
You are right. version 3.11 is fine.
